version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    command: bash -c "bundle install && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      RAILS_ENV: development